version: '2'
services:
  web:
    build: .
    command: npm run dev
    volumes:
      - C:\Users\tom.myers\Documents\Repos\nodejs\MusicManager
      - C:\Users\tom.myers\Documents\Repos\nodejs\MusicManager\node_modules
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://svc_user_musicman@postgres/musicmanager
  postgres:
    image: postgres:9.6.2-alpine
    environment:
      POSTGRES_USER: svc_user_musicman
      POSTGRES_DB: musicmanager
